
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app-deployment
spec:
  replicas: 2 # Number of desired replicas (adjust as needed)
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: fikunmisamson/my-express-app:1.0 
          ports:
            - containerPort: 3000 # The port Node.js app listens on


# apiVersion: v1
# kind: Service
# metadata:
#   name: my-node-service
# spec:
#   selector:
#     app: nodejs-app
#   ports:
#     - protocol: TCP
#       port: 3000
#       targetPort: 3000
#   type: LoadBalancer